pybase: don't use std::move to return std::optional
This fixes a gcc compiler warning:

    error: moving a temporary object prevents copy elision [-Werror=pessimizing-move]

Also make use of std::nullopt while we are touching this.