pybase: fix build with msvc v143
This fixes building with msvc v143. This fixes errors like:

    error C2275: 'py::pinterface_python_type<T>::abstract': expected an expression instead of a type

Apparently, being able to omit the typename keyword is a microsoft
extension (according to the clang compiler), so there are probably
other instances where we need to make a similar fix.